# Generated by Django 6.0.5 on 2026-05-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='Date_depart',
            new_name='date_depart',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='Titre',
            new_name='titre',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='descriptif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
