# Generated by Django 6.0.5 on 2026-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_rename_nom_categorie_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
